# fly.toml app configuration file generated for kebabot on 2023-06-19T20:14:03+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "kebabot"
primary_region = "cdg"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
